In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.15.0'

In [2]:
data = pd.read_csv("../../Data/Vaihingen/area2_cov_multi.csv", header=None)
data[['x', 'y', 'z', 'cl', 'cs', 'cp', 'class']] = data[0].str.split(' ', expand=True)
data = data.drop([0], axis=1)
data['x'] = data['x'].astype(float)
data['y'] = data['y'].astype(float)
data['z'] = data['z'].astype(float)
data['cl'] = data['cl'].astype(float)
data['cs'] = data['cs'].astype(float)
data['cp'] = data['cp'].astype(float)
data['class'] = data['class'].astype('category')
data= data.dropna()
data.head()

x        y         z   cl        cs        cp class
0  0.001387  1.10728  0.017115  0.0  0.112454  0.887546     2
1  0.001387  1.10974  0.017115  0.0  0.074641  0.925359     2
2  0.001541  1.11221  0.017115  0.0  0.074641  0.925359     2
3  0.001541  1.11221  0.017115  0.0  0.074641  0.925359     2
4  0.003545  1.11714  0.017115  0.0  0.493422  0.506578     2

In [3]:
# from my_utils import get_mu
# get_mu(data, 2)

In [4]:
X = data.drop('class', axis=1)
y = data['class']

In [5]:
y

0         2
1         2
2         2
3         2
4         2
         ..
266670    5
266671    8
266672    8
266673    8
266674    8
Name: class, Length: 266623, dtype: category
Categories (4, object): ['1', '2', '5', '8']

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
data["class_new"] = data['class'].cat.codes
# enc_data = pd.DataFrame(enc.fit_transform( 
#     data[['class_new']]).toarray()) 
  
# # Merge with main 
# New_df = data.join(enc_data)

In [7]:
# New_df =  New_df.drop(['class', 'class_new'], axis=1)
New_df = data
New_df= New_df.dropna()


In [8]:
New_df.columns

Index(['x', 'y', 'z', 'cl', 'cs', 'cp', 'class', 'class_new'], dtype='object')

In [9]:
New_df.shape

(266623, 8)

In [10]:
New_df

x        y         z        cl        cs        cp class  \
0       0.001387  1.10728  0.017115  0.000000  0.112454  0.887546     2   
1       0.001387  1.10974  0.017115  0.000000  0.074641  0.925359     2   
2       0.001541  1.11221  0.017115  0.000000  0.074641  0.925359     2   
3       0.001541  1.11221  0.017115  0.000000  0.074641  0.925359     2   
4       0.003545  1.11714  0.017115  0.000000  0.493422  0.506578     2   
...          ...      ...       ...       ...       ...       ...   ...   
266670  1.066120  1.76079  0.021406  0.304970  0.385871  0.309159     5   
266671  1.066280  1.76079  0.017115  0.270976  0.440006  0.289018     8   
266672  1.066430  1.76326  0.017115  0.295360  0.318112  0.386527     8   
266673  1.066430  1.76572  0.017115  0.233511  0.364512  0.401977     8   
266674  1.069670  1.76326  0.017115  0.233708  0.363608  0.402684     8   

        class_new  
0               1  
1               1  
2               1  
3               1  
4               1  
...           ...  
266670          2  
266671          3  
266672          3  
266673          3  
266674          3  

[266623 rows x 8 columns]

In [11]:
# X = New_df.drop([0, 1, 2, 3], axis=1)
# y = New_df[[0, 1, 2, 3]]

X = New_df.drop(['class', 'class_new'], axis=1)
y = New_df[['class_new']]

In [12]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [14]:
from gda import *

In [15]:
type(X_train)

pandas.core.frame.DataFrame

In [16]:
np.array(X_train)

array([[0.142417 , 1.31689  , 0.0171147, 0.       , 0.106064 , 0.893936 ],
       [0.592324 , 1.91862  , 0.0171147, 0.0769211, 0.0915776, 0.831501 ],
       [0.536067 , 1.29963  , 0.0840937, 0.0300696, 0.0239871, 0.945943 ],
       ...,
       [0.875    , 1.50185  , 0.0171147, 0.0386611, 0.0914347, 0.869904 ],
       [0.246455 , 1.0037   , 0.0171147, 0.0395252, 0.0521307, 0.908344 ],
       [0.823058 , 1.37855  , 0.0171147, 0.0547934, 0.0747722, 0.870434 ]])

In [17]:
y_train

class_new
6131            1
202178          1
74282           2
140316          3
122813          3
...           ...
211586          3
86313           3
122604          1
152343          3
117977          3

[213298 rows x 1 columns]

In [18]:
phi, mu, sigma = fit(np.array(X_train[['cl', 'cs', 'cp']]), np.array(y_train))

In [20]:
y_pred = predict(np.array(X_test[['cl', 'cs', 'cp']]), phi, mu, sigma)

In [ ]:
# ann = tf.keras.models.Sequential()

In [ ]:
# ann.add(tf.keras.layers.Conv3D(units=64, activation='relu', input_shape=))
# ann.add(tf.keras.layers.MaxPooling3D(units=32, activation='relu'))
# ann.add(tf.keras.layers.Conv3D(units=16, activation='relu'))
# ann.add(tf.keras.layers.MaxPooling3D(units=8, activation='relu'))
# ann.add(tf.keras.layers.Conv3D(units=4, activation='softmax'))

In [ ]:
# ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
# ann.fit(X_train, y_train, batch_size = 32, epochs = 15)


In [ ]:
# y_pred = ann.predict(X_test)

In [21]:
y_pred

array([1, 2, 1, ..., 1, 1, 2], dtype=int64)

In [ ]:
# res = y_pred.argmax(axis=1)

In [ ]:
# res

In [ ]:
# y_test1 = y_test.to_numpy()

In [ ]:
# y_test1 = y_test1.argmax(axis=1)

In [ ]:
# y_test1 = y_test1.astype(int)

In [ ]:
# print(y_test1.shape, res.shape)

In [ ]:
# print(np.concatenate((res.reshape(len(res),1), y_test1.reshape(len(y_test1),1)),1))

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[    0  7350   484     0]
 [    0  9592   619     0]
 [    0  5949  7841     0]
 [    0  2631 18859     0]]


0.32691983122362867